### ISSUE TITLE
Cleanup issue in 0.6.2 In 3.12

### ISSUE THREAD

**Issue by mikedh** [PyryM/xgpu#15]
When upgrading to `xgpu-0.6.2` *after* a successful run there appears to be a cleanup issue. I ran many times and observed these two messages (no idea why it switched between them):

Happened once:
```
corrupted double-linked list
Aborted (core dumped)
```

Happened nearly every time, run with `gdb -ex r --args python prog.py`

```
made it to end of analysis
wrote result to disc

malloc_consolidate(): unaligned fastbin chunk detected
Fatal Python error: Aborted

Current thread 0x00007f680f87c000 (most recent call first):
  Garbage-collecting
  <no Python frame>
Aborted (core dumped)

made it to end of analysis
wrote result to disc
[Thread 0x7fff51fdf640 (LWP 302118) exited]
malloc_consolidate(): unaligned fastbin chunk detected
[Thread 0x7fff527e0640 (LWP 302117) exited]

Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350225920) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.

```

I reverted to `xgpu-0.5.1` and was not able to reproduce this exit issue.

**Comment by mikedh** [comment]
Full backtrace:
```
made it to end of analysis
wrote result to disc
[Thread 0x7fff414de640 (LWP 305258) exited]
malloc_consolidate(): unaligned fastbin chunk detected
[Thread 0x7fff41cdf640 (LWP 305257) exited]

Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350225920) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350225920)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350225920) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350225920, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c88476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c6e7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7ccf676 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff7e21b77 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7ce6cfc in malloc_printerr (
    str=str@entry=0x7ffff7e245b8 "malloc_consolidate(): unaligned fastbin chunk detected")
    at ./malloc/malloc.c:5664
#7  0x00007ffff7ce798c in malloc_consolidate (av=av@entry=0x7ffff7e60c80 <main_arena>)
    at ./malloc/malloc.c:4750
#8  0x00007ffff7ce8ea0 in _int_free (av=0x7ffff7e60c80 <main_arena>, p=0x2ec03c0, 
    have_lock=<optimized out>) at ./malloc/malloc.c:4674
#9  0x00007ffff7ceb453 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#10 0x00007fff4314b202 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#11 0x00007fff4314ca24 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#12 0x00007fff43091d43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#13 0x00007fff8809c890 in ?? () from /lib/x86_64-linux-gnu/libEGL_mesa.so.0
#14 0x00007fff8808ee84 in ?? () from /lib/x86_64-linux-gnu/libEGL_mesa.so.0
#15 0x00007fff9f3a204a in <wgpu_hal::gles::egl::Inner as core::ops::drop::Drop>::drop ()
   from /home/mikedh/venv/lib/python3.12/site-packages/xgpu/libwgpu_native.so
#16 0x00007fff9f243764 in core::ptr::drop_in_place<core::option::Option<wgpu_hal::gles::egl::Instance>> () from /home/mikedh/venv/lib/python3.12/site-packages/xgpu/libwgpu_native.so
#17 0x00007fff9f248e08 in alloc::sync::Arc<T,A>::drop_slow ()
   from /home/mikedh/venv/lib/python3.12/site-packages/xgpu/libwgpu_native.so
#18 0x00007fff9f24a9d4 in alloc::sync::Arc<T,A>::drop_slow ()
   from /home/mikedh/venv/lib/python3.12/site-packages/xgpu/libwgpu_native.so
#19 0x00007fff9f1de193 in wgpuBindGroupLayoutRelease ()
   from /home/mikedh/venv/lib/python3.12/site-packages/xgpu/libwgpu_native.so
#20 0x00007fffa02c4def in _cffi_f_wgpuBindGroupLayoutRelease (self=<optimized out>, 
    arg0=0x7fff964ef2a0) at _wgpu_native_cffi.c:5239
#21 0x000000000057dac9 in ?? ()
#22 0x000000000057ea2d in ?? ()
#23 0x00000000006409ee in PyObject_CallFunctionObjArgs ()
#24 0x00007fffa027f67d in gcp_finalize (origobj=0x7fff964ef2a0, destructor=0x7fff964a4630)
    at src/c/_cffi_backend.c:2018
#25 cdatagcp_finalize (cd=<optimized out>) at src/c/_cffi_backend.c:2047
#26 0x00000000005692e0 in ?? ()
#27 0x0000000000674680 in ?? ()
#28 0x0000000000660bac in Py_FinalizeEx ()
#29 0x000000000066db2e in Py_RunMain ()
#30 0x000000000062aa1d in Py_BytesMain ()
#31 0x00007ffff7c6fd90 in __libc_start_call_main (main=main@entry=0x62a960, argc=argc@entry=2, 
    argv=argv@entry=0x7fffffffb768) at ../sysdeps/nptl/libc_start_call_main.h:58
#32 0x00007ffff7c6fe40 in __libc_start_main_impl (main=0x62a960, argc=2, argv=0x7fffffffb768, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffb758) at ../csu/libc-start.c:392
#33 0x000000000062a895 in _start ()
```

**Comment by mikedh** [comment]
After further debugging this issue only occurs on Python 3.12.

**Comment by PyryM** [comment]
Fixed with https://github.com/PyryM/xgpu/pull/19
